name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make -C n
      
    - name: Run check
      run: echo make check
      
    - name: Run distcheck
      run: echo make distcheck
